LouBuzReview/Controllers/WebUsersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using LouBuzReview.Data;
using LouBuzReview.Models;

namespace LouBuzReview.Controllers
{
    public class WebUsersController : Controller
    {
        private LouBuzReviewContext db = new LouBuzReviewContext();

        // GET: WebUsers
        public ActionResult Index(string searchName, string sortOrder)
        {
            ViewBag.NameSortParmFN = sortOrder == "NameFN" ? "nameDescFN" : "NameFN";
            ViewBag.NameSortParmLN = sortOrder == "NameLN" ? "nameDescLN" : "NameLN";
            ViewBag.NameSortParmCity = sortOrder == "NameCity" ? "nameDescCity" : "NameCity";
            ViewBag.NameSortParmState = sortOrder == "NameState" ? "nameDescState" : "NameState";
            //ViewBag.DateSortParm = sortOrder == "Date" ? "dateDesc" : "Date";

            var users = from u in db.WebUsers
                           select u;
            if(!String.IsNullOrEmpty(searchName))
            {
                users = users.Where(u =>
                    u.FirstName.ToLower().Contains(searchName.ToLower()) 
                    || 
                    u.LastName.ToLower().Contains(searchName.ToLower())
                    ||
                    u.City.ToLower().Contains(searchName.ToLower())); 
            }

            
            switch (sortOrder)
            {
                case "nameDescFN":
                    users = users.OrderByDescending(u => u.FirstName);
                    break;
                case "NameFN":
                    users = users.OrderBy(u => u.FirstName);
                    break;
                case "nameDescLN":
                    users = users.OrderByDescending(u => u.LastName);
                    break;
                case "NameLN":
                    users = users.OrderBy(u => u.LastName);
                    break;
                case "nameDescCity":
                    users = users.OrderByDescending(u => u.City);
                    break;
                case "nameCity":
                    users = users.OrderBy(u => u.City);
                    break;
                case "nameDescState":
                    users = users.OrderByDescending(u => u.State);
                    break;
                case "nameState":
                    users = users.OrderBy(u => u.State);
                    break;                
                default:
                    break;
            }
            return View(users.ToList());
        }

        // GET: WebUsers/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            WebUser webUser = db.WebUsers.Find(id);
            if (webUser == null)
            {
                return HttpNotFound();
            }
            return View(webUser);
        }

        // GET: WebUsers/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: WebUsers/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "UserID,FirstName,LastName,City,State")] WebUser webUser)
        {
            if (ModelState.IsValid)
            {
                db.WebUsers.Add(webUser);
                db.SaveChanges();
                return RedirectToAction("Create");
            }

            return View(webUser);
        }

        // GET: WebUsers/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            WebUser webUser = db.WebUsers.Find(id);
            if (webUser == null)
            {
                return HttpNotFound();
            }
            return View(webUser);
        }

        // POST: WebUsers/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "UserID,FirstName,LastName,City,State")] WebUser webUser)
        {
            if (ModelState.IsValid)
            {
                db.Entry(webUser).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(webUser);
        }

        // GET: WebUsers/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            WebUser webUser = db.WebUsers.Find(id);
            if (webUser == null)
            {
                return HttpNotFound();
            }
            return View(webUser);
        }

        // POST: WebUsers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            WebUser webUser = db.WebUsers.Find(id);
            db.WebUsers.Remove(webUser);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult TabView(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            WebUser webUser = db.WebUsers.Find(id);
            if (webUser == null)
            {
                return HttpNotFound();
            }
            return View(webUser);
        }
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

LouBuzReview/Controllers/WebsiteReviewsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using LouBuzReview.Data;
using LouBuzReview.Models;
using LouBuzReview.ViewModels;

namespace LouBuzReview.Controllers
{
    public class WebsiteReviewsController : Controller
    {
        private LouBuzReviewContext db = new LouBuzReviewContext();

        // GET: WebsiteReviews
        public ActionResult Index(string searchName)
        {
            var websiteReviews = db.WebsiteReviews.Include(r => r.WebUser).Include(r => r.Website);

            if (!String.IsNullOrEmpty(searchName))
            {
                websiteReviews = websiteReviews.Where(w =>
                    w.WebUser.FirstName.ToLower().Contains(searchName.ToLower())
                    ||
                    w.WebUser.LastName.ToLower().Contains(searchName.ToLower())
                    ||
                    w.Website.WebsiteName.ToLower().Contains(searchName.ToLower()) 
                    ||
                    w.Ratings.ToString().ToLower().Contains(searchName.ToLower()));
            }
            return View(websiteReviews.ToList());
        }

        // GET: WebsiteReviews/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var websiteReview = db.WebsiteReviews
                .Include(r => r.WebUser)
                .Include(r => r.Website)
                .Where(r => r.ID == id)
                .FirstOrDefault();

            if (websiteReview == null)
            {
                return HttpNotFound();
            }
            return View(websiteReview);
        }

        // GET: WebsiteReviews/Create
        public ActionResult Create()
        {
            ViewBag.WebsiteID = new SelectList(db.Websites, "WebsiteID", "WebsiteUrl");
            ViewBag.UserID = new SelectList(db.WebUsers, "UserID", "FirstName");
            return View();
        }

        // POST: WebsiteReviews/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,UserID,WebsiteID,Ratings,UserReview,CreatedDate")] WebsiteReview websiteReview)
        {
            if (ModelState.IsValid)
            {
                db.WebsiteReviews.Add(websiteReview);
                db.SaveChanges();
                TempData["Message"] = "Review was successfully added";
                return RedirectToAction("Index");
            }

            ViewBag.WebsiteID = new SelectList(db.Websites, "WebsiteID", "WebsiteUrl", websiteReview.WebsiteID);
            ViewBag.UserID = new SelectList(db.WebUsers, "UserID", "FirstName", websiteReview.UserID);
            return View(websiteReview);
        }


        // GET: WebsiteReviews/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            WebsiteReview websiteReview = db.WebsiteReviews.Find(id);
            if (websiteReview == null)
            {
                return HttpNotFound();
            }
            ViewBag.WebsiteID = new SelectList(db.Websites, "WebsiteID", "WebsiteID", websiteReview.WebsiteID);
            ViewBag.UserID = new SelectList(db.WebUsers, "UserID", "UserID", websiteReview.UserID);
            return View(websiteReview);
        }

        // POST: WebsiteReviews/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(WebsiteReview websiteReview)
        {
            if (ModelState.IsValid)
            {                
                db.Entry(websiteReview).State = EntityState.Modified;
                //Confirm  WebUser table as edited
                db.Entry(websiteReview.WebUser).State = EntityState.Modified;
                //Confirm  WebUser table as edited
                db.Entry(websiteReview.Website).State = EntityState.Modified;
                db.SaveChanges(); 
                //Captures tempdata from server to display operation completed successfully
                TempData["Message"] = "Edited Review was successfully Saved";
                return RedirectToAction("Index");
            }
            
            return View(websiteReview);
        }

        // GET: WebsiteReviews/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            WebsiteReview websiteReview = db.WebsiteReviews.Find(id);
            if (websiteReview == null)
            {
                return HttpNotFound();
            }
            return View(websiteReview);
        }

        // POST: WebsiteReviews/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            //select the record for the id passed to delete from WebsiteReviews table
            WebsiteReview websiteReview = db.WebsiteReviews.Find(id);
            //Get the related primary key of Webuser  
            var userid = websiteReview.WebUser.UserID;
            //Get the related primary key of Website  
            var websiteid = websiteReview.Website.WebsiteID;
            //find record for the selected Primary Keys
            Website website = db.Websites.Find(websiteid);
            WebUser webuser = db.WebUsers.Find(userid);
            //Removing records from respective tables
            db.WebsiteReviews.Remove(websiteReview);
            db.Websites.Remove(website);
            db.WebUsers.Remove(webuser);
            //save the database
            db.SaveChanges();
            //Captures tempdata from server to display operation completed successfully
            TempData["Message"] = "Review was successfully deleted";
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

LouBuzReview/Controllers/WebsitesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using LouBuzReview.Data;
using LouBuzReview.Models;

namespace LouBuzReview.Controllers
{
    public class WebsitesController : Controller
    {
        private LouBuzReviewContext db = new LouBuzReviewContext();

        // GET: Websites
        public ActionResult Index(string searchName)
        {
            var websites = from w in db.Websites
                        select w;
            if (!String.IsNullOrEmpty(searchName))
            {
                websites = websites.Where(w =>
                    w.WebsiteName.ToLower().Contains(searchName.ToLower())
                    ||
                    w.WebsiteUrl.ToLower().Contains(searchName.ToLower()));
            }
            return View(websites.ToList());
        }

        // GET: Websites/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Website website = db.Websites.Find(id);
            if (website == null)
            {
                return HttpNotFound();
            }
            return View(website);
        }

        // GET: Websites/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Websites/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "WebsiteID,Category,WebsiteUrl,WebsiteName")] Website website)
        {
            if (ModelState.IsValid)
            {
                db.Websites.Add(website);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(website);
        }

        // GET: Websites/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Website website = db.Websites.Find(id);
            if (website == null)
            {
                return HttpNotFound();
            }
            return View(website);
        }

        // POST: Websites/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "WebsiteID,Category,WebsiteUrl,WebsiteName")] Website website)
        {
            if (ModelState.IsValid)
            {
                db.Entry(website).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(website);
        }

        // GET: Websites/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Website website = db.Websites.Find(id);
            if (website == null)
            {
                return HttpNotFound();
            }
            return View(website);
        }

        // POST: Websites/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Website website = db.Websites.Find(id);
            db.Websites.Remove(website);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

LouBuzReview/Views/Shared/_Header.cshtml
<div class="main-header">
    <div class="container header-title ">
        <h1 class="header-title">LouBuzReview</h1>
        <h3 class="col-md-6">
            Louisville Business Review is public website for rating the businesses in Louisville 
            and their services by anyone. It is free and use this service to rate any business located in Louisville.
        </h3>
    </div>
</div>

LouBuzReview/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Louisville Web Review</title>

    <link rel="stylesheet" href="CSS/normalize.css">
    <link href="~/CSS/bootstrap.min.css" rel="stylesheet" type="text/css">
    <link href="~/CSS/bootstrap-datepicker3.min.css" rel="stylesheet" type="text/css">
    <link href="~/CSS/styles.css" rel="stylesheet">
    @*<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">*@
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" />
    <link href="https://fonts.googleapis.com/css?family=Aref+Ruqaa|Oregano" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Galada|Great+Vibes|Monoton" rel="stylesheet">
    <!-- JQuery -->
    
</head>
<body>
    <nav>
        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    @Html.ActionLink("LBR", "Index", "Home", new { area = "" }, new { @class = "navbar-brand header-title-h1" })
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li class="">@Html.ActionLink("Home", "Index", "Home")</li>
                        <li>@Html.ActionLink("User Profiles", "Index", "WebUsers")</li>
                        <li>@Html.ActionLink("Registered Businesses", "Index", "Websites")</li>
                        <li>@Html.ActionLink("User Reviews", "Index", "WebsiteReviews")</li>
                    </ul>
                    <div class="col-sm-3 col-md-3 pull-right">
                        <form class="navbar-form" role="search">
                            <div class="input-group">
                                <input type="text" class="form-control" placeholder="Search" name="SearchName" id="SearchName">
                                <div class="input-group-btn">
                                    <button class="btn btn-default" type="submit"><i class="glyphicon glyphicon-search"></i></button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </nav>

    <div>
        @Html.Partial("_Header")
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />

    </div>

    <div class="panel-footer navbar-fixed-bottom " style="background-color:black;">
        <footer>
            <div style="background-color:black;">

                <div class="container text-bold" style="background-color:black;">
                    <ul>
                        <li>&copy; @DateTime.Now.Year - Dhanapala Godage </li>
                        <li> Louisville Busness Review</li>
                    </ul>

                </div>

            </div>
        </footer>
    </div>
    <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/Scripts/bootstrap-datepicker.min.js"></script>
    @*<script src="https://use.fontawesome.com/releases/v5.0.6/js/all.js"></script>*@
    @*<script>
            $('input.datepicker').datepicker({ format: mm / dd / yyyy });
        </script>*@

</body>
</html>